### ISSUE TITLE
RuleErrored not enough information

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#135]
### Version

0.3.2-SNAPSHOT

### Reproduction steps

1. File `.github/workflows/x.yml` with the following content:
   ```yaml
   on: push
   jobs:
     repro:
       runs-on: ubuntu-latest
       steps:
         - run: echo "Problem!"
   ```

2. Run `ghlint` with the following arguments:
   ```shell
   ghlint --console .github/workflows/x.yml
   ```

### Expected behavior

Stack trace in help or detail message?

### Actual behavior

https://github.com/TWiStErRob/net.twisterrob.ghlint/security/code-scanning/87

![image](https://github.com/TWiStErRob/net.twisterrob.ghlint/assets/2906988/63d8ce72-2eb4-4d8e-b41f-38c44df9394e)

### Additional Context

 * Does not tell which file failed.
 * Big title
 * Stack trace unformatted in message
