### ISSUE TITLE
InvalidStepReference

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#145]
```yaml
steps:
  - id: x
  - env:
      X: ${{ steps.y.outputs.xxx }}
```

Regex for: `steps.(*).outputs.*` and check if `()` part exists.
