### ISSUE TITLE
New rule: RedundantGitHubWorkspace

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#167]
```
        uses: actions/upload-artifact@v4
        with:
          name: 'ShellCheck Results'
          path: ${{ github.workspace }}/shellcheck.*
```

should be:
```
        uses: actions/upload-artifact@v4
        with:
          name: 'ShellCheck Results'
          path: shellcheck.*
```
recommend also to always `|` for "escaping"
