### ISSUE TITLE
Concurrency on specific branches is probably a problem

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#240]
```
on:
  push:
    branches: 
      - 'main'
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

This suggests that the workflow will run on "trunk-like" branches. This is usually done to populate caches, and baselines. Adding a concurrency on it will mean that not every commit on the trunk is branch-able.
