### ISSUE TITLE
Flag not enough permissions when doing actions/checkout

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#285]
ref i-11204

Potentially other things too. There could be a known list of things with permissions required.

```
permissions:
  pull-requests: write
steps:
  - uses: actions/checkout@v4
    # without token:!
```
