### ISSUE TITLE
Validate Inputs use supported types

### ISSUE THREAD

**Issue by timsearle** [TWiStErRob/net.twisterrob.ghlint#301]
[Supported Types](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context)

Invalid example:

```yaml
on:
  workflow_call:
    inputs:
      some-value:
        type: number
```

Valid example:

```yaml
on:
  workflow_call:
    inputs:
      some-value:
        type: string
```
