### ISSUE TITLE
Input dependencies

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#338]
Example:

```yaml
  uses: nick-fields/retry@v3
  with:
    max_attempts: 3
    command: ...
```

```
Error: Must specify either timeout_minutes or timeout_seconds inputs
```
