### ISSUE TITLE
ExtraPermissions: called workflow doesn't need it

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#532]
```
uses: x.yml
permissions:
  contents: read
  actions: write
```

x.yml
```
jobs:
  job:
    permissions:
      actions: read
```

contents: read is redundant, and actions: write is too broad
